// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDec2ePbslXALC1JzCwfNRJmiRE8GUHLwk',
    appId: '1:982632217071:web:8c80f68b298122b1d0de1a',
    messagingSenderId: '982632217071',
    projectId: 'chat-app-676ee',
    authDomain: 'chat-app-676ee.firebaseapp.com',
    storageBucket: 'chat-app-676ee.firebasestorage.app',
    measurementId: 'G-BW2TYM4K3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2o0xwdUBMQFab5RNpriD_s1vfi1nNJiE',
    appId: '1:982632217071:android:1ac616e080dfdf62d0de1a',
    messagingSenderId: '982632217071',
    projectId: 'chat-app-676ee',
    storageBucket: 'chat-app-676ee.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDec2ePbslXALC1JzCwfNRJmiRE8GUHLwk',
    appId: '1:982632217071:web:431bded6fe4f3048d0de1a',
    messagingSenderId: '982632217071',
    projectId: 'chat-app-676ee',
    authDomain: 'chat-app-676ee.firebaseapp.com',
    storageBucket: 'chat-app-676ee.firebasestorage.app',
    measurementId: 'G-WK6F5Q7KPR',
  );
}
